spring:
  application:
    name: gateway

server:
  port: 11000

jwt:
  token:
    creator: closet
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '3000'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'

management:
  endpoints:
    web:
      exposure:
        include: "*"
