apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze-deployment
  namespace: kopo-trainee20
  labels:
    app: analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyze
  template:
    metadata:
      labels:
        app: analyze
    spec:
      containers:
        - name: analyze
          image: docker.io/jiheonk/analyze:v22
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 15000
---
apiVersion: v1
kind: Service
metadata:
  name: analyze-service
  namespace: kopo-trainee20
  labels:
    app: analyze
spec:
  selector:
    app: analyze
  ports:
    - protocol: TCP
      port: 15000
      targetPort: 15000
  type: LoadBalancer
