apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: kopo-trainee20
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front-container
          image: docker.io/jiheonk/front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12000

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: kopo-trainee20
  labels:
    app: front
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
