apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: kopo-trainee20
  labels:
    app: front
    environment: production
data:
  application.yml: |
    server:
      port: 12000
    spring:
      application:
        name: front
      kafka:
        bootstrap-servers: 223.130.147.174:9092
        consumer:
          group-id: analyze-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          properties:
            spring.json.trusted.packages: "*"
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
    jwt:
      token:
        creator: pm
        refresh:
          valid:
            time: '3000'
          name: jwtRefreshToken
        access:
          valid:
            time: '3000'
          name: jwtAccessToken
      secret:
        key: '12345678123456781234567812345678123456781234'
    management:
      endpoints:
        web:
          exposure:
            include: "*"

---
apiVersion: v1
kind: Secret
metadata:
  name: front-secret
  namespace: kopo-trainee20
type: Opaque
data:
  jwt-secret-key: MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2NzgxMjM0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: kopo-trainee20
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front-container
          image: docker.io/jiheonk/front:latest
          ports:
            - containerPort: 12000
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: front-secret
                  key: jwt-secret-key
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: front-config

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: kopo-trainee20
  labels:
    app: front
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
