apiVersion: apps/v1
kind: Deployment
metadata:
  name: prevention-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prevention
  template:
    metadata:
      labels:
        app: prevention
    spec:
      containers:
        - name: prevention
          image: docker.io/jiheonk/prevention:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 14000
---
apiVersion: v1
kind: Service
metadata:
  name: prevention-service
spec:
  selector:
    app: prevention
  ports:
    - protocol: TCP
      port: 14000
      targetPort: 14000
  type: LoadBalancer
