server:
  port: 14000

spring:
  application:
    name: prevention

  # JPA
  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    properties:
      hibernate:
        default_batch_fetch_size: '100'
        format_sql: 'true'
        use_sql_comments: 'true'

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: pm
    password: 1234
    url: jdbc:mariadb://198.19.161.97:3306/pm

management:
  endpoints:
    web:
      exposure:
        include: "*"