server:
  port: 13000

spring:
  application:
    name: user
  data:
    redis:
#      host: 198.19.172.224
      host: localhost
      port: 6379
      password: 1234

  # JPA ??
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
    open-in-view: false
  datasource:
    username: pm
    password: '1234'
#    url: jdbc:postgresql://198.19.211.209:5432/pm
    url: jdbc:postgresql://localhost:15432/pm
    driver-class-name: org.postgresql.Driver

# JWT ?? ??
jwt:
  token:
    creator: pm
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '3000'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'

management:
  endpoints:
    web:
      exposure:
        include: "*"