spring:
  application:
    name: AnalyzeService
  elasticsearch:
    uris: https://localhost:9200  # Elasticsearch 서버 주소
    host: localhost
    port: 9200
    username: elastic  # 사용자 이름
    password: 1234  # 비밀번호
    connection-timeout: 3s  # 연결 시간 초과 설정 (선택 사항)
    socket-timeout: 3s  # 소켓 시간 초과 설정 (선택 사항)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyze-group
      auto-offset-reset: earliest  # 필요한 경우 'latest'로 설정 가능
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 11000

ncp:
  objectStorage:
    endPoint: "https://kr.object.ncloudstorage.com"
    regionName: "kr-standard"
    accessKey: "gtiHaVgTnYHFkX6aRzLu"
    secretKey: "eNVqarObDsvHvamFovccIAcUQFFcOzcsKg4CCrI1"
    bucketName: "pro-memoria24"
