spring:
  application:
    name: AnalyzeService
  elasticsearch:
    uris: https://localhost:9200  # Elasticsearch 서버 주소
    host: localhost
    port: 9200
    username: elastic  # 사용자 이름
    password: 1234  # 비밀번호
    connection-timeout: 3s  # 연결 시간 초과 설정 (선택 사항)
    socket-timeout: 3s  # 소켓 시간 초과 설정 (선택 사항)

ncp:
  objectStorage:
    endPoint: "https://kr.object.ncloudstorage.com"
    regionName: "kr-standard"
    accessKey: "gtiHaVgTnYHFkX6aRzLu"
    secretKey: "eNVqarObDsvHvamFovccIAcUQFFcOzcsKg4CCrI1"
    bucketName: "pro-memoria24"